Repository richiepagard/fun-with-python, pull requests merged in 2025-09, with the labels that each got.

#6 Add PR(Pull Request) Default Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#13 Separating The Main Function
  python-unittest/authentication-logic/authentication/authentication.py
Labels: enhancement

#17 Add `CODEOWNERS` File.
  .github/CODEOWNERS
Labels: documentation

#18 Unit Test -> User AuthenticationFix Match-Case Bug and Test Case For Passwords
  python-unittest/authentication-logic/authentication/authentication.py
  python-unittest/authentication-logic/tests/__init__.py
  python-unittest/authentication-logic/tests/test_authentication.py
  string-wizard/get-url_subdomain/__init__.py
  string-wizard/get-url_subdomain/get_subdomain.py
Labels: bug, enhancement, test case
